// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkmmwvotkcdputijttzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrbW13dm90a2NkcHV0aWp0dHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0Nzc4MTIsImV4cCI6MjA4OTA1MzgxMn0.95bZG6Ea5c3rVTMEigxCSjTsLb3gZamABp2u9VI80uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});